# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(918, 571)
        self.main_display = QtWidgets.QLabel(MainWindow)
        self.main_display.setGeometry(QtCore.QRect(10, 10, 640, 480))
        self.main_display.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_display.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.main_display.setAlignment(QtCore.Qt.AlignCenter)
        self.main_display.setObjectName("main_display")
        self.frame_vid_con = QtWidgets.QFrame(MainWindow)
        self.frame_vid_con.setGeometry(QtCore.QRect(270, 500, 251, 61))
        self.frame_vid_con.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_vid_con.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_vid_con.setObjectName("frame_vid_con")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_vid_con)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_frame_prev = QtWidgets.QPushButton(self.frame_vid_con)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_frame_prev.sizePolicy().hasHeightForWidth())
        self.btn_frame_prev.setSizePolicy(sizePolicy)
        self.btn_frame_prev.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_frame_prev.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_frame_prev.setObjectName("btn_frame_prev")
        self.horizontalLayout_2.addWidget(self.btn_frame_prev)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_frame_num = QtWidgets.QLabel(self.frame_vid_con)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_frame_num.setFont(font)
        self.label_frame_num.setScaledContents(False)
        self.label_frame_num.setAlignment(QtCore.Qt.AlignCenter)
        self.label_frame_num.setObjectName("label_frame_num")
        self.horizontalLayout_2.addWidget(self.label_frame_num)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btn_frame_next = QtWidgets.QPushButton(self.frame_vid_con)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_frame_next.sizePolicy().hasHeightForWidth())
        self.btn_frame_next.setSizePolicy(sizePolicy)
        self.btn_frame_next.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_frame_next.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_frame_next.setObjectName("btn_frame_next")
        self.horizontalLayout_2.addWidget(self.btn_frame_next)
        self.frame_folder = QtWidgets.QFrame(MainWindow)
        self.frame_folder.setGeometry(QtCore.QRect(660, 10, 251, 80))
        self.frame_folder.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_folder.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_folder.setObjectName("frame_folder")
        self.frame_folder_name = QtWidgets.QFrame(self.frame_folder)
        self.frame_folder_name.setGeometry(QtCore.QRect(0, 0, 191, 81))
        self.frame_folder_name.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_folder_name.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_folder_name.setObjectName("frame_folder_name")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_folder_name)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_dir_title = QtWidgets.QLabel(self.frame_folder_name)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_dir_title.setFont(font)
        self.label_dir_title.setObjectName("label_dir_title")
        self.verticalLayout.addWidget(self.label_dir_title)
        self.label_dir_name = QtWidgets.QLabel(self.frame_folder_name)
        self.label_dir_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_dir_name.setObjectName("label_dir_name")
        self.verticalLayout.addWidget(self.label_dir_name)
        self.btn_load_sequence = QtWidgets.QPushButton(self.frame_folder)
        self.btn_load_sequence.setGeometry(QtCore.QRect(200, 20, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btn_load_sequence.setFont(font)
        self.btn_load_sequence.setObjectName("btn_load_sequence")
        self.frame_clear = QtWidgets.QFrame(MainWindow)
        self.frame_clear.setGeometry(QtCore.QRect(540, 500, 111, 61))
        self.frame_clear.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_clear.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_clear.setObjectName("frame_clear")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_clear)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_copy_labels = QtWidgets.QPushButton(self.frame_clear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_copy_labels.sizePolicy().hasHeightForWidth())
        self.btn_copy_labels.setSizePolicy(sizePolicy)
        self.btn_copy_labels.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_copy_labels.setObjectName("btn_copy_labels")
        self.horizontalLayout_3.addWidget(self.btn_copy_labels)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.btn_clear_labels = QtWidgets.QPushButton(self.frame_clear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_clear_labels.sizePolicy().hasHeightForWidth())
        self.btn_clear_labels.setSizePolicy(sizePolicy)
        self.btn_clear_labels.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_clear_labels.setObjectName("btn_clear_labels")
        self.horizontalLayout_3.addWidget(self.btn_clear_labels)
        self.frame_label = QtWidgets.QFrame(MainWindow)
        self.frame_label.setGeometry(QtCore.QRect(10, 500, 251, 61))
        self.frame_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_label.setObjectName("frame_label")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_label)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_color = QtWidgets.QLabel(self.frame_label)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_color.sizePolicy().hasHeightForWidth())
        self.label_color.setSizePolicy(sizePolicy)
        self.label_color.setMaximumSize(QtCore.QSize(40, 22))
        self.label_color.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_color.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_color.setAlignment(QtCore.Qt.AlignCenter)
        self.label_color.setObjectName("label_color")
        self.horizontalLayout_4.addWidget(self.label_color)
        self.cbox_select_label = QtWidgets.QComboBox(self.frame_label)
        self.cbox_select_label.setObjectName("cbox_select_label")
        self.horizontalLayout_4.addWidget(self.cbox_select_label)
        self.btn_edit_label = QtWidgets.QPushButton(self.frame_label)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_edit_label.sizePolicy().hasHeightForWidth())
        self.btn_edit_label.setSizePolicy(sizePolicy)
        self.btn_edit_label.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_edit_label.setObjectName("btn_edit_label")
        self.horizontalLayout_4.addWidget(self.btn_edit_label)
        self.table_filename = QtWidgets.QTableWidget(MainWindow)
        self.table_filename.setGeometry(QtCore.QRect(660, 100, 250, 460))
        self.table_filename.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_filename.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_filename.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_filename.setObjectName("table_filename")
        self.table_filename.setColumnCount(2)
        self.table_filename.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_filename.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_filename.setHorizontalHeaderItem(1, item)
        self.table_filename.horizontalHeader().setDefaultSectionSize(120)
        self.table_filename.horizontalHeader().setStretchLastSection(True)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ultrasound Pixel Labeler"))
        self.main_display.setText(_translate("MainWindow", "Main Image Frame"))
        self.btn_frame_prev.setText(_translate("MainWindow", "Prev"))
        self.label_frame_num.setText(_translate("MainWindow", "0/0"))
        self.btn_frame_next.setText(_translate("MainWindow", "Next"))
        self.label_dir_title.setText(_translate("MainWindow", "Current Directory"))
        self.label_dir_name.setText(_translate("MainWindow", "..."))
        self.btn_load_sequence.setText(_translate("MainWindow", "Load"))
        self.btn_copy_labels.setText(_translate("MainWindow", "Copy"))
        self.btn_clear_labels.setText(_translate("MainWindow", "Clear"))
        self.label_color.setText(_translate("MainWindow", "Color"))
        self.btn_edit_label.setText(_translate("MainWindow", "Edit"))
        item = self.table_filename.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Filename"))
        item = self.table_filename.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Labeled"))

